name: transposo
description: "Transposo: Sheet Music Transposer — the ultimate transposing tool for musicians."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  webview_flutter: ^4.10.0
  http: ^1.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/abcjs_template.html
    - assets/abcjs-basic-min.js
